#!/bin/bash

# Menu tonen
function show_menu(){
date
echo "Menu"
echo "---------------------------"
echo "1. Server registreren"
echo "2. Vagrant box beheer"
echo "3. Remote execution van commando's/scripts op servers"
echo "4. Monitoring van de remote hosts"
echo "5. Enkele predefined architecturen opzetten in vagrant"
echo "7. Exit"
}
