#!/bin/bash

# Menu tonen
function show_menu(){
date
echo "Menu"
echo "---------------------------"
echo "1. Server registreren"
echo "2. Vagrant box beheer"
echo "3. Remote execution van commando's/scripts op servers"
echo "4. Monitoring van de remote hosts"
echo "5. Enkele predefined architecturen opzetten in vagrant"
echo "6. Exit"
}

optie = int(input('Wat wil je doen?'))
   #Ip adres en servernaam opslaan
   if optie == 1:
       class host:
          def __init__(self, server, ip):
             self.server = server
             self.ip = ip
          def __str__(self):
             return self.server

       class hostFileLezen:
          def __init__(self):
              self.filename = "servers.config"
          def leesFile(self):
              data = []
              try:
                  # print(filename)
                  with open(self.filename, "r") as f:
                      print('reading file')
                      data = f.readlines()
                      print(data)
                      hostlist = []
                      for i in data:
                          info = i.split(';')
                          nhost = host(info[0].strip(), info[1].strip())
                          hostlist.append(nhost)

                      return hostlist
              except:
                  return ['failed', data]
	show_menu()
   elif optie == 2:
   #Uitwerken optie 3
   elif optie == 3:
         def menu():
         print('1. Netmiko\n2. Script uitvoeren op remote server\n3. Terug naar menu')
         optie = int(input('Geef uw keuze in'))
         #Netmiko
         if optie == 1:
               from netmiko import ConnectHandler
               params = {
                  'device_type': 'linux',
                  'ip': '192.168.33.10',
                  'username': 'user',
                  'password': 'password',
                  'secret': 'password',
                  'port': '22'
                  }
                myssh = ConnectHandler(**params)
                output_pwd = myssh.send_command("pwd")
                print(output_pwd)
         #Script uitvoeren op remote server
         elif optie == 2:
                 server_ip=$1
                 file_to_execute=$2

                 if [ -n "$1" ]; then
                     echo "Connectie maken met server $1"
                 else
                     echo "Geef een server IP!"
                     exit 1
                 fi

                 if [ -n "$2" ]; then
                     echo "Script uitvoeren $2"
                 else
                     echo "Geef een bestand om uit te voeren!"
                     exit 1
                 fi
                 shift
                 shift
                 ssh ${server_ip} "bash -s" -- < ${file_to_execute} $*
         #Terug naar hoofdmenu        
         elif optie == 3:
                 show_menu()
         #Terug naar submenu
         else:
             print('Geef een geldig nummer in\n')
             menu()
   #Monitoring van de remote hosts
   elif optie == 4:
           server_name=$(hostname)
           function ram_check() {
             echo "#######"
	          echo "The current memory usage on ${server_name} is: "
	          free -h
	          echo "#######"
           }
           function cpu_check() {
             echo "#######"
	          echo "The current CPU load on ${server_name} is: "
	          uptime
             echo "#######"
           }
           function disk_check() {
             echo "#######"
	          echo "The current disk usage on ${server_name} is: "
	          df -h
             echo "#######"
           }
           function process_check() {
           echo "#######"
           echo "The current active tasks on ${server_name} is: "
           tasklist
           echo "#######"
           }
           function all_checks() {
           ram_check
           cpu_check
           disk_check
           process_check
           }
	   show_menu()
   elif optie == 5:
   elif optie == 6:
      
   else:
        print('please give a valid number\n')
        show_menu()
